### ISSUE TITLE
Unable to cast object of type 'ECDsaSecurityTransforms' to type 'System.Security.Cryptography.ECDsaCng'.

### ISSUE THREAD

**Issue by WouterHD** [abergs/fido2-net-lib#133]
### Description
Trying to register a YubiKey 4 as a 2FA throws an invalidcastexception.

### Code Used
Code used to produce the exception:
```
var parsed = AuthenticatorAttestationResponse.Parse(attestationResponse);
var success = parsed.VerifyAsync(
	options,
	new Fido2Configuration {
		ServerName = "Fido 2 local test",
		ServerDomain = "localhost",
		Origin = "https://localhost:63536",
	},
	(x) => Task.FromResult(true), // callback,
	null,
	null);
```
OR
```
var success = await fidoLib.MakeNewCredentialAsync(attestationResponse, options, callback);
```

### Parameter Values
AuthenticatorAttestationRawResponse attestationResponse as Json:
```
{
  "Extensions": {
    "appid": false,
    "authnSel": false,
    "biometricPerfBounds": false
  },
  "Id": "cgwCz28pJtwpIpYjxvkMYzxxJk279q2lWF_4K_EmTSMUGplrdCTv-KGn6glBrc1jd10dLuAJY2wVgy-Ct1xZrQ",
  "RawId": "cgwCz28pJtwpIpYjxvkMYzxxJk279q2lWF_4K_EmTSMUGplrdCTv-KGn6glBrc1jd10dLuAJY2wVgy-Ct1xZrQ",
  "Response": {
    "AttestationObject": "o2NmbXRoZmlkby11MmZnYXR0U3RtdKJjc2lnWEYwRAIgXH6YWrE9Qc7_q5UH0fRROUq6Rl1zqneHegP8oLx_RskCIDzK8tHqPbywvXMHihhTpWPNMCU-_iqIvWALrGNfouZuY3g1Y4FZAk4wggJKMIIBMqADAgECAgRXFvfAMA0GCSqGSIb3DQEBCwUAMC4xLDAqBgNVBAMTI1l1YmljbyBVMkYgUm9vdCBDQSBTZXJpYWwgNDU3MjAwNjMxMCAXDTE0MDgwMTAwMDAwMFoYDzIwNTAwOTA0MDAwMDAwWjAsMSowKAYDVQQDDCFZdWJpY28gVTJGIEVFIFNlcmlhbCAyNTA1NjkyMjYxNzYwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARk2RxU1tlXjdOwYHhMRjbVSKOYOq81J87rLcbjK2eeM_zp6GMUrbz4V1IbL0xJn5SvcFVlviIZWym2Tk2tDdBiozswOTAiBgkrBgEEAYLECgIEFTEuMy42LjEuNC4xLjQxNDgyLjEuNTATBgsrBgEEAYLlHAIBAQQEAwIFIDANBgkqhkiG9w0BAQsFAAOCAQEAeJsYypuk23Yg4viLjP3pUSZtKiJ31eP76baMmqDpGmpI6nVM7wveWYQDba5_i6P95ktRdgTDoRsubXVNSjcZ76h2kw-g4PMGP1pMoLygMU9_BaPqXU7dkdNKZrVdXI-obgDnv1_dgCN-s9uCPjTjEmezSarHnCSnEqWegEqqjWupJSaid6dx3jFqc788cR_FTSJmJ_rXleT0ThtwA08J_P44t94peJP7WayLHDPPxca-XY5Mwn9KH0b2-ET4eMByi9wd-6Zx2hCH9Yzjjllro_Kf0FlBXcUKoy-JFHzT2wgBN9TmW7zrC7_lQYgYjswUMRh5UZKrOnOHqaVyfxBIhmhhdXRoRGF0YVjESZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2NBAAAAAAAAAAAAAAAAAAAAAAAAAAAAQHIMAs9vKSbcKSKWI8b5DGM8cSZNu_atpVhf-CvxJk0jFBqZa3Qk7_ihp-oJQa3NY3ddHS7gCWNsFYMvgrdcWa2lAQIDJiABIVggdNuG2tgs9Gxjgg30RMCcwrMd6Uovuv4QuUZlGr6tllwiWCDXHPD4i32zwChY7KvGuOSAOupKJpvod0zZX-y8DlQZkQ",
    "ClientDataJson": "eyJjaGFsbGVuZ2UiOiJNYmVpcXp3S0xpSGNKYUY1WGpDeVpBIiwiZXh0cmFfa2V5c19tYXlfYmVfYWRkZWRfaGVyZSI6ImRvIG5vdCBjb21wYXJlIGNsaWVudERhdGFKU09OIGFnYWluc3QgYSB0ZW1wbGF0ZS4gU2VlIGh0dHBzOi8vZ29vLmdsL3lhYlBleCIsIm9yaWdpbiI6Imh0dHBzOi8vbG9jYWxob3N0OjYzNTM2IiwidHlwZSI6IndlYmF1dGhuLmNyZWF0ZSJ9"
  },
  "Type": "public-key"
}
```

CredentialCreateOptions options as Json: 
```
{
    "rp": {
        "id": "localhost",
        "name": "Fido 2 local test"
    },
    "user": {
        "name": "testing@evidos.nl",
        "id": "YjYzYzMyZDU1ODI5NDUzZmFlY2JhZDQ5NjdjMDRkYmM",
        "displayName": "testing@evidos.nl"
    },
    "challenge": "lr7HiuNiDw9ThdDpQhjpfA",
    "pubKeyCredParams": [
        {
            "type": "public-key",
            "alg": -7
        },
        {
            "type": "public-key",
            "alg": -257
        },
        {
            "type": "public-key",
            "alg": -37
        },
        {
            "type": "public-key",
            "alg": -35
        },
        {
            "type": "public-key",
            "alg": -258
        },
        {
            "type": "public-key",
            "alg": -38
        },
        {
            "type": "public-key",
            "alg": -36
        },
        {
            "type": "public-key",
            "alg": -259
        },
        {
            "type": "public-key",
            "alg": -39
        }
    ],
    "timeout": 60000,
    "attestation": "direct",
    "authenticatorSelection": {
        "requireResidentKey": false,
        "userVerification": "discouraged"
    },
    "excludeCredentials": [
        {
            "type": "public-key",
            "id": "AZMCIBCLkeohptOEnL3Y6irnVdcbnvro3X1PcifZdg2OG28tfq4raUhUmpjEIZh5MZm2BagibXhg6qcWNuqEklYPCnC8loXQ18DRmkRlTG85VRdr-IU7C7tAMi0diKQprU8rqaM"
        }
    ],
    "extensions": {
        "exts": true,
        "uvi": true,
        "loc": true,
        "uvm": true,
        "biometricPerfBounds": {
            "FAR": 3.40282347e+38,
            "FRR": 3.40282347e+38
        }
    },
    "status": "ok",
    "errorMessage": ""
}
```

### Exception thrown
This throws an InvalidCastException:
```
Exception has occurred: CLR/System.AggregateException
Exception thrown: 'System.AggregateException' in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.InvalidCastException : Unable to cast object of type 'ECDsaSecurityTransforms' to type 'System.Security.Cryptography.ECDsaCng'.
   at Fido2NetLib.AttestationFormat.FidoU2f.Verify()
   at Fido2NetLib.AuthenticatorAttestationResponse.<VerifyAsync>d__10.MoveNext()
```

**Comment by aseigler** [comment]
What platform and build are you using?  At a glance this looks identical to #70 which should have been resolved by #132.

**Comment by WouterHD** [comment]
macOS Mojave version 10.14.6
Visual Studio Code version 1.39.0
<TargetFramework>netcoreapp2.1</TargetFramework>
<PackageReference Include="Fido2" Version="1.0.1" />

**Comment by aseigler** [comment]
Pretty sure it will. @abergs?

**Comment by abergs** [comment]
@WouterHD Please test this preview release and report back if it works for you: https://www.nuget.org/packages/Fido2/1.1.0-preview1

**Comment by WouterHD** [comment]
@abergs I was able to both register and verify my Yubikeys using the new release 🎉 
Tested with firefox and chrome on MacOs

**Comment by abergs** [comment]
Great. scheduling a release in about 1 week to allow for feedback from others.

**Comment by WouterHD** [comment]
Looks like there's another dependency on ECDsaCng in the Fido2MetadataServiceRepository, throws the same exception when trying to create a MetadataService. Similar fix to #132 ?

**Comment by aseigler** [comment]
Yes, I missed that one. Will check in a fix in a couple of hours. Thanks!

**Comment by aseigler** [comment]
This should be good now.  @abergs, can you please push another preview release out?

**Comment by abergs** [comment]
@WouterHD A new preview package has been pushed and should be available soon: https://www.nuget.org/packages/Fido2/1.1.0-preview2

**Comment by abergs** [comment]
@WouterHD I'm holding off with releasing until you give the thumbs up 👍

**Comment by WouterHD** [comment]
Getting the following exception upon MetadataService initialization
`System.IndexOutOfRangeException: Index was outside the bounds of the array.`

On this code fragment:
```
var metadataRepos = new List<IMetadataRepository>{
	new Fido2MetadataServiceRepository(
		accessToken: "<AccessToken Redacted>",
		httpClient: new System.Net.Http.HttpClient())
};

metadataService = new SimpleMetadataService(metadataRepos);

if (!metadataService.IsInitialized()) {
	metadataService.Initialize().Wait();
}
```


Full stacktrace:
```
System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Fido2NetLib.CryptoUtils.CDPFromCertificateExts(X509ExtensionCollection exts)
   at Fido2NetLib.Fido2MetadataServiceRepository.DeserializeAndValidateToc(String toc)
   at Fido2NetLib.Fido2MetadataServiceRepository.GetToc()
   at Fido2NetLib.SimpleMetadataService.InitializeClient(IMetadataRepository repository)
   at Fido2NetLib.SimpleMetadataService.Initialize()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Signhost.Auth.UI.Controllers.WebAuthnController..ctor(IConfiguration config, IClientStore clientStore, IUserCredentialRepository userCredentialRepository, IDataProtectionProvider dataProtectorProvider) in /Users/wouterbrouwer/Documents/signhost-auth/src/Signhost.Auth.UI/Controllers/WebAuthnController.cs:line 60
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
```
