### ISSUE TITLE
Unit test failure when running tests locally

### ISSUE THREAD

**Issue by kennep** [abergs/fido2-net-lib#185]
When running the unit tests locally, 7 unit tests under "Packed" fail. However, I see that the same tests run successfully on Azure DevOps. So _something_ is different here.

What I've tried:
* `dotnet test` on Linux
* Running the tests in Rider on Linux
* Running the tests in Visual Studio 2019 on Windows

In all these three cases, the same 7 tests fail.

Environment:
```
$ dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
$ dotnet --list-sdks
3.1.401 [/usr/share/dotnet/sdk]
```

Test log:
```
$ dotnet test
Test run for /home/kenneth/Projects/Vipps/fido2-net-lib/Test/bin/Debug/netcoreapp3.1/Test.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:09.42]     Test.Attestation.Packed.TestFullAttCertNotV3 [FAIL]
[xUnit.net 00:00:09.43]     Test.Attestation.Packed.TestFullInvalidAlg [FAIL]
[xUnit.net 00:00:09.43]     Test.Attestation.Packed.TestFullAttCertSubject [FAIL]
  X Test.Attestation.Packed.TestFullAttCertNotV3 [8ms]
  Error Message:
   Assert.Equal() Failure
                 ↓ (pos 7)
Expected: Packed x5c attestation certificate not V3
Actual:   Packed signing certificate expired or not yet va···
                 ↑ (pos 7)
  Stack Trace:
     at Test.Attestation.Packed.TestFullAttCertNotV3() in /home/kenneth/Projects/Vipps/fido2-net-lib/Test/Attestation/Packed.cs:line 893
  X Test.Attestation.Packed.TestFullInvalidAlg [7ms]
  Error Message:
   System.AggregateException : One or more errors occurred. (Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   typeof(Fido2NetLib.Fido2VerificationException): Packed signing certificate expired or not yet valid)
---- Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   typeof(Fido2NetLib.Fido2VerificationException): Packed signing certificate expired or not yet valid
-------- Fido2NetLib.Fido2VerificationException : Packed signing certificate expired or not yet valid
  Stack Trace:
     at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Test.Attestation.Packed.TestFullInvalidAlg() in /home/kenneth/Projects/Vipps/fido2-net-lib/Test/Attestation/Packed.cs:line 763
----- Inner Stack Trace -----
   at Fido2NetLib.AttestationFormat.Packed.Verify() in /home/kenneth/Projects/Vipps/fido2-net-lib/Src/Fido2/AttestationFormat/Packed.cs:line 79
   at Fido2NetLib.AuthenticatorAttestationResponse.VerifyAsync(CredentialCreateOptions originalOptions, Fido2Configuration config, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, IMetadataService metadataService, Byte[] requestTokenBindingId) in /home/kenneth/Projects/Vipps/fido2-net-lib/Src/Fido2/AuthenticatorAttestationResponse.cs:line 167
   at Fido2NetLib.Fido2.MakeNewCredentialAsync(AuthenticatorAttestationRawResponse attestationResponse, CredentialCreateOptions origChallenge, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, Byte[] requestTokenBindingId) in /home/kenneth/Projects/Vipps/fido2-net-lib/Src/Fido2/Fido2NetLib.cs:line 74
   at fido2_net_lib.Test.Fido2Tests.Attestation.MakeAttestationResponse() in /home/kenneth/Projects/Vipps/fido2-net-lib/Test/Fido2Tests.cs:line 284
----- Inner Stack Trace -----
   at Fido2NetLib.AttestationFormat.Packed.Verify() in /home/kenneth/Projects/Vipps/fido2-net-lib/Src/Fido2/AttestationFormat/Packed.cs:line 79
   at Fido2NetLib.AuthenticatorAttestationResponse.VerifyAsync(CredentialCreateOptions originalOptions, Fido2Configuration config, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, IMetadataService metadataService, Byte[] requestTokenBindingId) in /home/kenneth/Projects/Vipps/fido2-net-lib/Src/Fido2/AuthenticatorAttestationResponse.cs:line 167
   at Fido2NetLib.Fido2.MakeNewCredentialAsync(AuthenticatorAttestationRawResponse attestationResponse, CredentialCreateOptions origChallenge, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, Byte[] requestTokenBindingId) in /home/kenneth/Projects/Vipps/fido2-net-lib/Src/Fido2/Fido2NetLib.cs:line 74
   at fido2_net_lib.Test.Fido2Tests.Attestation.MakeAttestationResponse() in /home/kenneth/Projects/Vipps/fido2-net-lib/Test/Fido2Tests.cs:line 284
  X Test.Attestation.Packed.TestFullAttCertSubject [4ms]
  Error Message:
   Assert.Equal() Failure
          ↓ (pos 0)
Expected: Invalid attestation cert subject
Actual:   Packed signing certificate expired or not···
          ↑ (pos 0)
  Stack Trace:
     at Test.Attestation.Packed.TestFullAttCertSubject() in /home/kenneth/Projects/Vipps/fido2-net-lib/Test/Attestation/Packed.cs:line 953
[xUnit.net 00:00:11.03]     Test.Attestation.Packed.TestFull [FAIL]
[xUnit.net 00:00:11.04]     Test.Attestation.Packed.TestFullAttCertCAFlagSet [FAIL]
[xUnit.net 00:00:11.05]     Test.Attestation.Packed.TestFullAttCertAaguidNotMatchAuthdata [FAIL]
  X Test.Attestation.Packed.TestFull [1s 158ms]
  Error Message:
   System.ArgumentException : Key already exists
  Stack Trace:
     at PeterO.Cbor.CBORObject.Add(Object key, Object valueOb)
   at Test.Attestation.Packed.<TestFull>b__9_0(Object[] param) in /home/kenneth/Projects/Vipps/fido2-net-lib/Test/Attestation/Packed.cs:line 260
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
  X Test.Attestation.Packed.TestFullAttCertCAFlagSet [4ms]
  Error Message:
   Assert.Equal() Failure
          ↓ (pos 0)
Expected: Attestion certificate has CA cert flag pr···
Actual:   Packed signing certificate expired or not···
          ↑ (pos 0)
  Stack Trace:
     at Test.Attestation.Packed.TestFullAttCertCAFlagSet() in /home/kenneth/Projects/Vipps/fido2-net-lib/Test/Attestation/Packed.cs:line 1074
  X Test.Attestation.Packed.TestFullAttCertAaguidNotMatchAuthdata [4ms]
  Error Message:
   Assert.Equal() Failure
          ↓ (pos 0)
Expected: aaguid present in packed attestation cert···
Actual:   Packed signing certificate expired or not···
          ↑ (pos 0)
  Stack Trace:
     at Test.Attestation.Packed.TestFullAttCertAaguidNotMatchAuthdata() in /home/kenneth/Projects/Vipps/fido2-net-lib/Test/Attestation/Packed.cs:line 1015
[xUnit.net 00:00:11.07]     Test.Attestation.Packed.TestFullInvalidSig [FAIL]
  X Test.Attestation.Packed.TestFullInvalidSig [4ms]
  Error Message:
   Assert.Equal() Failure
          ↓ (pos 0)
Expected: Invalid full packed signature
Actual:   Packed signing certificate expired or not···
          ↑ (pos 0)
  Stack Trace:
     at Test.Attestation.Packed.TestFullInvalidSig() in /home/kenneth/Projects/Vipps/fido2-net-lib/Test/Attestation/Packed.cs:line 822

Test Run Failed.
Total tests: 197
     Passed: 190
     Failed: 7
 Total time: 18.6250 Seconds
/usr/share/dotnet/sdk/3.1.401/Microsoft.TestPlatform.targets(32,5): error MSB4181: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task returned false but did not log an error. [/home/kenneth/Projects/Vipps/fido2-net-lib/Test/Test.csproj]
```

**Comment by aseigler** [comment]
All of your failures are hitting [this certificate time validation check](https://github.com/abergs/fido2-net-lib/blob/7305982fc38094b04324a12846e92fa2b96b7820/Src/Fido2/AttestationFormat/Packed.cs#L77) where they should be passing that part and failing later checks.  What's really odd is that none of the certs used for these tests are hard coded, they are generated on the fly in the tests using a [not before of DateTimeOffset.UtcNow and a not after of DateTimeOffset.UtcNow.AddDays(2)](https://github.com/abergs/fido2-net-lib/blob/7305982fc38094b04324a12846e92fa2b96b7820/Test/Attestation/Packed.cs#L832).  Even if the date/time was way off for some reason on your machine, it wouldn't make any difference since they would still be time valid locally.

**Comment by kennep** [comment]
Thanks! This gave me the clues I needed to figure it out. Turns out there was a comparison between a local DateTime and an UTC Datetime, which will not give the expected results when the machine is not set to the UTC time zone. This also explains why it works on Azure DevOps (where the build agent _is_ set to UTC.)

I submitted PR #186 as a fix for this.
