### ISSUE TITLE
Windows Cryptography Next Generation (CNG) is not supported on this platform

### ISSUE THREAD

**Issue by idaviddesmet** [abergs/fido2-net-lib#70]
I couldn't run all tests (6 failed) since I was getting several `PlatformNotSupportedException` like the one mentioned in the title.

The tests were executed in macOS but could probably fail in Linux due to Windows-specific CNG.
I could take a more in deep look in case you can't test in a platform other than Windows.

I would also like to suggest creating Linux and macOS specific build pipelines each one executing the tests in order to make sure it passes on all platforms. Perhaps the following [yaml](https://github.com/idaviddesmet/NaCl.Core/blob/master/azure-pipelines.yml) could be of any help on giving a hint on creating those platform-specific pipelines (not an expert here, it took me quite some tries to get it working on my side)?

**Comment by abergs** [comment]
Good idea with the pipelines.
It would be interesting to see what methods / code paths are failing if you could run it with a debugger?

**Comment by idaviddesmet** [comment]
No problem, I will track those lines and report back when I get the results. ;)

**Comment by idaviddesmet** [comment]
Apologies for getting back until now, it was quite busy at work...
I have got the stack trace from running against the latest commit:

```bash
----- Test Execution Summary -----
    
fido2_net_lib.Test.UnitTest1.TestU2FAttestationAsync:
    Outcome: Failed
    Error Message:
    System.InvalidCastException : Unable to cast object of type 'ECDsaSecurityTransforms' to type 'System.Security.Cryptography.ECDsaCng'.
    Stack Trace:
       at Fido2NetLib.AttestationFormat.FidoU2f.Verify() in /Users/dds/Projects/fido2-net-lib/fido2-net-lib/AttestationFormat/FidoU2f.cs:line 68
   at Fido2NetLib.AuthenticatorAttestationResponse.VerifyAsync(CredentialCreateOptions originalOptions, String expectedOrigin, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, IMetadataService metadataService, Byte[] requestTokenBindingId) in /Users/dds/Projects/fido2-net-lib/fido2-net-lib/AuthenticatorAttestationResponse.cs:line 164
   at fido2_net_lib.Test.UnitTest1.TestU2FAttestationAsync() in /Users/dds/Projects/fido2-net-lib/fido2-net-lib.Test/UnitTest1.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
    
fido2_net_lib.Test.UnitTest1.TestAndroidKeyAttestationAsync:
    Outcome: Failed
    Error Message:
    Fido2NetLib.Fido2VerificationException : Failed to extract public key from android keyUnable to cast object of type 'ECDsaSecurityTransforms' to type 'System.Security.Cryptography.ECDsaCng'.
    Stack Trace:
       at Fido2NetLib.AttestationFormat.AndroidKey.Verify() in /Users/dds/Projects/fido2-net-lib/fido2-net-lib/AttestationFormat/AndroidKey.cs:line 201
   at Fido2NetLib.AuthenticatorAttestationResponse.VerifyAsync(CredentialCreateOptions originalOptions, String expectedOrigin, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, IMetadataService metadataService, Byte[] requestTokenBindingId) in /Users/dds/Projects/fido2-net-lib/fido2-net-lib/AuthenticatorAttestationResponse.cs:line 164
   at fido2_net_lib.Test.UnitTest1.TestAndroidKeyAttestationAsync() in /Users/dds/Projects/fido2-net-lib/fido2-net-lib.Test/UnitTest1.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
    
fido2_net_lib.Test.UnitTest1.TestPackedAttestationAsync:
    Outcome: Failed
    Error Message:
    System.InvalidCastException : Unable to cast object of type 'ECDsaSecurityTransforms' to type 'System.Security.Cryptography.ECDsaCng'.
    Stack Trace:
       at Fido2NetLib.AttestationFormat.Packed.Verify() in /Users/dds/Projects/fido2-net-lib/fido2-net-lib/AttestationFormat/Packed.cs:line 64
   at Fido2NetLib.AuthenticatorAttestationResponse.VerifyAsync(CredentialCreateOptions originalOptions, String expectedOrigin, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, IMetadataService metadataService, Byte[] requestTokenBindingId) in /Users/dds/Projects/fido2-net-lib/fido2-net-lib/AuthenticatorAttestationResponse.cs:line 164
   at fido2_net_lib.Test.UnitTest1.TestPackedAttestationAsync() in /Users/dds/Projects/fido2-net-lib/fido2-net-lib.Test/UnitTest1.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
    
fido2_net_lib.Test.UnitTest1.TestParsingAsync:
    Outcome: Failed
    Error Message:
    System.InvalidCastException : Unable to cast object of type 'ECDsaSecurityTransforms' to type 'System.Security.Cryptography.ECDsaCng'.
    Stack Trace:
       at Fido2NetLib.AttestationFormat.FidoU2f.Verify() in /Users/dds/Projects/fido2-net-lib/fido2-net-lib/AttestationFormat/FidoU2f.cs:line 68
   at Fido2NetLib.AuthenticatorAttestationResponse.VerifyAsync(CredentialCreateOptions originalOptions, String expectedOrigin, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, IMetadataService metadataService, Byte[] requestTokenBindingId) in /Users/dds/Projects/fido2-net-lib/fido2-net-lib/AuthenticatorAttestationResponse.cs:line 164
   at fido2_net_lib.Test.UnitTest1.TestParsingAsync() in /Users/dds/Projects/fido2-net-lib/fido2-net-lib.Test/UnitTest1.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
```
As you can see, the issue is mainly around ECDsaCng as it is an ECDSA implementation using Windows CNG. It's specific to Windows, so not supported on Linux nor macOS.

**Comment by idaviddesmet** [comment]
Fixing the exception from TestTPMSHA256AttestationAsync and TestTPMSHA1AttestationAsync wasn't much of an issue, but they now fail with the following new exception:

```bash
Fido2NetLib.Fido2VerificationException : SAN missing TPMManufacturer, TPMModel, or TPMVersion from TPM attestation certificate
```

The returned SAN value is now `DirName:<unsupported>`.
The fix can be found in the [latest commit from hotfix/cross-platform-crypto](https://github.com/idaviddesmet/fido2-net-lib/commit/4a0005e70fd5bfeecd28e811ff4303ada59ecade) branch.

**Comment by bdangh** [comment]
I have similar issue, Windows Hello is not working when hosted on Linux.

**Comment by aseigler** [comment]
I have a build now that is fully working on Linux server. There are only a few parts that needed remediation. Should have a workable solution soon.

**Comment by bdangh** [comment]
Any chance to get NuGet with this fix?

**Comment by aseigler** [comment]
> Any chance to get NuGet with this fix?

@abergs?

**Comment by abergs** [comment]
Yes! Let me look into it tomorrow 
    	
    	

    	/Anders (from phone)
    
  




On Fri, Oct 25, 2019 at 9:18 PM +0200, "Alex Seigler" <notifications@github.com> wrote:













Any chance to get NuGet with this fix?



@abergs?

**Comment by abergs** [comment]
@aseigler @bdangh Please test this preview release: https://www.nuget.org/packages/Fido2/1.1.0-preview1
